# Sprint Runner - Automated Implementation Orchestrator
name: sprint-runner
description: 'Fully automated orchestrator that loops through stories: create-story → dev-story → code-review (up to 3 attempts). Runs subagents for each workflow, stays lightweight, logs progress to orchestrator.md.'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/_bmad/bmm/config.yaml'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
implementation_artifacts: '{config_source}:implementation_artifacts'
planning_artifacts: '{config_source}:planning_artifacts'

# Workflow components
installed_path: '{project-root}/_bmad/bmm/workflows/4-implementation/sprint-runner'
instructions: '{installed_path}/instructions.md'

# Key files
sprint_status_file: '{implementation_artifacts}/sprint-status.yaml'
orchestrator_log: '{implementation_artifacts}/orchestrator.md'

# No validation checklist - orchestrator is coordination only
standalone: true
