name: sprint-create-story-discovery
description: 'Generate discovery files for stories in parallel with story creation - DISCOVERY ONLY mode'
author: 'BMad'

# Critical variables from config
config_source: '{project-root}/_bmad/bmm/config.yaml'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated
planning_artifacts: '{config_source}:planning_artifacts'
implementation_artifacts: '{config_source}:implementation_artifacts'
output_folder: '{implementation_artifacts}'

# Workflow components - minimal, no template needed
installed_path: '{project-root}/_bmad/bmm/workflows/4-implementation/sprint-runner/commands/sprint-create-story-discovery'
instructions: '{installed_path}/instructions.xml'

# Variables provided by orchestrator injection
variables:
  story_keys: '' # Comma-separated story keys (e.g., "2a-1,2a-2")
  epic_id: '' # Epic identifier (e.g., "2a")

# Sprint-runner specific - context injected via --prompt-system-append
# No template.md - discovery format defined in instructions
# No checklist.md - simplified validation in instructions

standalone: true
